name: DeadByDaylight
version: '${project.version}'
main: org.rednero.deadbydaylight.DeadByDaylight
author: RedNero
description: A Dead By Daylight plugin that allows you to experience the game in Minecraft!
commands:
  dbd:
    description: Dead By Daylight main command
    usage: /dbd
    aliases: [deadbydaylight]
