game:
  minPlayers: 2
  waitingForPlayersTime: 30
  fullLobbyTime: 10
  endingTime: 10
  hooks: 10
  generators: 5
  exitGates: 2
  chests: 4
  totems: 5
  generatorRepairTime: 10
  exitGateOpenTime: 5
  hatch: true
messages:
  prefix: '&7&l[&cDeadByDaylight&7&l]&r '
  joinedMessage: '&aYou joined the lobby!'
  joinedSpectatorMessage: '&aYou joined the lobby as a spectator!'
  leftMessage: '&cYou left the lobby!'
  unknownCommand: '&cUnknown command! Use &7/dbd help &cfor help.'
  unknownAdminCommand: '&cUnknown command! Use &7/dbd admin help &cfor help.'
  consoleCommand: '&cYou can''t use this command in console!'
  playerNotFound: '&cPlayer not found!'
  notInLobby: '&cYou are not in a lobby!'
  alreadyInLobby: '&cYou are already in a lobby!'
  lobbyFull: '&cThe lobby is full!'
  gameAlreadyStarted: '&cThe game has already started!'
  killerLeft: '&cThe killer %killer% left the game!'
  survivorLeft: '&cThe survivor %survivor% left the game!'
  noSurvivorsLeft: '&cThere are no survivors left!'
  noSpawnPointSpawn: '&cThe lobby spawnpoint is not set!'
  noSpawnPointSpectator: '&cThe spectator spawnpoint is not set!'
  notEnoughSpawnPointsKiller: '&cThere are not enough spawnpoints for the killer!'
  notEnoughSpawnPointsSurvivor: '&cThere are not enough spawnpoints for the survivors!'
  notEnoughChests: '&cThere are not enough chests!'
  notEnoughGenerators: '&cThere are not enough generators!'
  notEnoughHooks: '&cThere are not enough hooks!'
  notEnoughExitGates: '&cThere are not enough exit gates!'
  notEnoughTotems: '&cThere are not enough totems!'
  noHatch: '&cThe hatch is not set!'
  adminSetCommandUsage: '&cUsage: /dbd admin set <lobby|spectator>'
  unknownAdminSetCommand: '&cUnknown command! Use &7/dbd admin set &cfor help.'
  adminSetLobbyCommandSuccess: '&aLobby spawnpoint set!'
  adminSetSpectatorCommandSuccess: '&aSpectator spawnpoint set!'
  adminAddCommandUsage: '&cUsage: /dbd admin add <generator|chest|hook|exitgate|totem|hatch|killer|survivor>'
  unknownAdminAddCommand: '&cUnknown command! Use &7/dbd admin add &cfor help.'
  adminAddCreateUsage: '&aRight click with the stick to create a %type% spawnpoint.'
  adminAddKillerCommandSuccess: '&aKiller spawnpoint created!'
  adminAddSurvivorCommandSuccess: '&aSurvivor spawnpoint created!'
  generatorAdded: '&aGenerator added!'
  chestAdded: '&aChest added!'
  hookAdded: '&aHook added!'
  exitGateAdded: '&aExit gate added!'
  totemAdded: '&aTotem added!'
  hatchAdded: '&aHatch added!'
  adminRemoveCommandUsage: '&cUsage: /dbd admin remove <generator|chest|hook|exitgate|totem|hatch|killer|survivor> <id>'
  adminRemoveIdNotFound: '&cID not found!'
  adminRemoveSuccess: '&a%type% %id% removed!'
  unknownAdminRemoveCommand: '&cUnknown command! Use &7/dbd admin remove &cfor help.'
  adminListCommandUsage: '&cUsage: /dbd admin list <generators|chests|hooks|exitgates|totems|hatches|killers|survivors>'
  listItemsIntro: '&2List of %type%:'
  listItems: '&2ID: &f%id% &7- &2Spawnpoint: &f%spawnpoint%'
  unknownAdminListCommand: '&cUnknown command! Use &7/dbd admin list &cfor help.'
  typeSignNotSpecified: '&cYou must specify the type of sign (join, leave, stats, spectate).'
  noPermissionToPlaceSign: '&cYou don''t have permission to place this sign!'
  noPermissionToBreakSign: '&cYou don''t have permission to break this sign!'
  noPermissionToUseCommand: '&cYou don''t have permission to use this command!'
  noPermission: '&cYou don''t have permission to do this!'
  comingSoon: '&cComing soon...'
  helpCommand:
    - '&2DeadByDaylight commands:'
    - '&2/dbd help &r- &7show this message'
    - '&2/dbd join &r- &7join the lobby'
    - '&2/dbd leave &r- &7leave the game'
    - '&2/dbd spectate &r- &7spectate the game'
    - '&2/dbd stats &r- &7show your stats'
    - '&2/dbd stats <player> &r- &7show stats of a player'
  adminHelpCommand:
    - '&2DeadByDaylight admin commands:'
    - '&2/dbd admin help &r- &7show this message'
    - '&2/dbd admin set &r- &7set the lobby or spectator spawnpoint'
    - '&2/dbd admin add &r- &7add a generator, chest, hook, exit gate, totem or hatch'
    - '&2/dbd admin remove &r- &7remove a generator, chest, hook, exit gate, totem or hatch'
    - '&2/dbd admin list &r- &7list generators, chests, hooks, exit gates, totems or hatches'
  showAdminCommands: '&2/dbd admin &r- &7show admin commands'
signs:
  joinSign:
    - '&7&l[&cDBD&7&l]'
    - '&aJoin'
    - '&7Right click to'
    - '&7join.'
  leaveSign:
    - '&7&l[&cDBD&7&l]'
    - '&cLeave'
    - '&7Right click to'
    - '&7leave.'
  statsSign:
    - '&7&l[&cDBD&7&l]'
    - '&6Stats'
    - '&7Right click to'
    - '&7see your stats.'
  spectateSign:
    - '&7&l[&cDBD&7&l]'
    - '&7Spectate'
    - '&7Right click to'
    - '&7spectate.'